<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /home/seamus/buildkit/build/47-test/sites/default/files/civicrm/ext/au.org.greens.civigeometry/xml/schema/CRM/CiviGeometry/GeometryEntity.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:7739ce09b3abf0b119a051da808191a6)
 */

/**
 * Database access object for the GeometryEntity entity.
 */
class CRM_CiviGeometry_DAO_GeometryEntity extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civigeometry_geometry_entity';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique GeometryEntity ID
   *
   * @var int
   */
  public $id;

  /**
   * entity id that is associated with this geometry
   *
   * @var int
   */
  public $entity_id;

  /**
   * entity table that is associated with this geometry
   *
   * @var string
   */
  public $entity_table;

  /**
   * FK to Geometry Table
   *
   * @var int
   */
  public $geometry_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civigeometry_geometry_entity';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'geometry_id', 'civigeometry_geometry', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_CiviGeometry_ExtensionUtil::ts('Unique GeometryEntity ID'),
          'required' => TRUE,
          'where' => 'civigeometry_geometry_entity.id',
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_CiviGeometry_ExtensionUtil::ts('entity id that is associated with this geometry'),
          'required' => TRUE,
          'where' => 'civigeometry_geometry_entity.entity_id',
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => CRM_CiviGeometry_ExtensionUtil::ts('Entity Table'),
          'description' => CRM_CiviGeometry_ExtensionUtil::ts('entity table that is associated with this geometry'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civigeometry_geometry_entity.entity_table',
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
        ],
        'geometry_id' => [
          'name' => 'geometry_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_CiviGeometry_ExtensionUtil::ts('FK to Geometry Table'),
          'required' => TRUE,
          'where' => 'civigeometry_geometry_entity.geometry_id',
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
          'FKClassName' => 'CRM_CiviGeometry_DAO_Geometry',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'etry_geometry_entity', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'etry_geometry_entity', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_geometry_id_entity_id_entity_table' => [
        'name' => 'UI_geometry_id_entity_id_entity_table',
        'field' => [
          0 => 'geometry_id',
          1 => 'entity_id',
          2 => 'entity_table',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civigeometry_geometry_entity::1::geometry_id::entity_id::entity_table',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
