<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from au.org.greens.civigeometry/xml/schema/CRM/CiviGeometry/Geometry.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:26998ebb213bbf12a7c407b781fe0d94)
 */
use CRM_CiviGeometry_ExtensionUtil as E;

/**
 * Database access object for the Geometry entity.
 */
class CRM_CiviGeometry_DAO_Geometry extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civigeometry_geometry';

  /**
   * Field to show when displaying a record.
   *
   * @var string
   */
  public static $_labelField = 'label';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Geometry ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Geometry Type of this geometry type
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $geometry_type_id;

  /**
   * The Title of this geometry
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $label;

  /**
   * The description of this geometry
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $description;

  /**
   * Is this geometry archived?
   *
   * @var bool|string|null
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_archived;

  /**
   * The Title of this geometry
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $archived_date;

  /**
   * The Spatial data for this geometry
   *
   * @var string
   *   (SQL type: geometry)
   *   Note that values will be retrieved from the database as a string.
   */
  public $geometry;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civigeometry_geometry';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Geometries') : E::ts('Geometry');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'geometry_type_id', 'civigeometry_geometry_type', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Geometry ID'),
          'required' => TRUE,
          'where' => 'civigeometry_geometry.id',
          'table_name' => 'civigeometry_geometry',
          'entity' => 'Geometry',
          'bao' => 'CRM_CiviGeometry_DAO_Geometry',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'geometry_type_id' => [
          'name' => 'geometry_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Geometry Type'),
          'description' => E::ts('Geometry Type of this geometry type'),
          'where' => 'civigeometry_geometry.geometry_type_id',
          'table_name' => 'civigeometry_geometry',
          'entity' => 'Geometry',
          'bao' => 'CRM_CiviGeometry_DAO_Geometry',
          'localizable' => 0,
          'FKClassName' => 'CRM_CiviGeometry_DAO_GeometryType',
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'keyColumn' => 'id',
            'labelColumn' => 'label',
          ],
          'add' => NULL,
        ],
        'label' => [
          'name' => 'label',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Label'),
          'description' => E::ts('The Title of this geometry'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civigeometry_geometry.label',
          'table_name' => 'civigeometry_geometry',
          'entity' => 'Geometry',
          'bao' => 'CRM_CiviGeometry_DAO_Geometry',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Description'),
          'description' => E::ts('The description of this geometry'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civigeometry_geometry.description',
          'default' => NULL,
          'table_name' => 'civigeometry_geometry',
          'entity' => 'Geometry',
          'bao' => 'CRM_CiviGeometry_DAO_Geometry',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'is_archived' => [
          'name' => 'is_archived',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Archived'),
          'description' => E::ts('Is this geometry archived?'),
          'where' => 'civigeometry_geometry.is_archived',
          'default' => '0',
          'table_name' => 'civigeometry_geometry',
          'entity' => 'Geometry',
          'bao' => 'CRM_CiviGeometry_DAO_Geometry',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
          ],
          'add' => NULL,
        ],
        'archived_date' => [
          'name' => 'archived_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Archived Date'),
          'description' => E::ts('The Title of this geometry'),
          'required' => FALSE,
          'where' => 'civigeometry_geometry.archived_date',
          'default' => NULL,
          'table_name' => 'civigeometry_geometry',
          'entity' => 'Geometry',
          'bao' => 'CRM_CiviGeometry_DAO_Geometry',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'geometry' => [
          'name' => 'geometry',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Geometry'),
          'description' => E::ts('The Spatial data for this geometry'),
          'required' => TRUE,
          'where' => 'civigeometry_geometry.geometry',
          'table_name' => 'civigeometry_geometry',
          'entity' => 'Geometry',
          'bao' => 'CRM_CiviGeometry_DAO_Geometry',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'etry_geometry', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'etry_geometry', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_is_archived_geometry_type_label' => [
        'name' => 'index_is_archived_geometry_type_label',
        'field' => [
          0 => 'is_archived',
          1 => 'geometry_type_id',
          2 => 'label',
        ],
        'localizable' => FALSE,
        'sig' => 'civigeometry_geometry::0::is_archived::geometry_type_id::label',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
