<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from au.org.greens.civigeometry/xml/schema/CRM/CiviGeometry/GeometryEntity.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:cf7b679738ca1b82e9896b8d82f979aa)
 */
use CRM_CiviGeometry_ExtensionUtil as E;

/**
 * Database access object for the GeometryEntity entity.
 */
class CRM_CiviGeometry_DAO_GeometryEntity extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civigeometry_geometry_entity';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique GeometryEntity ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * entity id that is associated with this geometry
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_id;

  /**
   * entity table that is associated with this geometry
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_table;

  /**
   * FK to Geometry Table
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $geometry_id;

  /**
   * When Should this geometry entity relationship expire
   *
   * @var string
   *   (SQL type: timestamp)
   *   Note that values will be retrieved from the database as a string.
   */
  public $expiry_date;

  /**
   * The reason for the relationship between the geometry and entity
   *
   * @var string
   *   (SQL type: varchar(0))
   *   Note that values will be retrieved from the database as a string.
   */
  public $reason;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civigeometry_geometry_entity';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Geometry Entities') : E::ts('Geometry Entity');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'geometry_id', 'civigeometry_geometry', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique GeometryEntity ID'),
          'required' => TRUE,
          'where' => 'civigeometry_geometry_entity.id',
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Entity ID'),
          'description' => E::ts('entity id that is associated with this geometry'),
          'required' => TRUE,
          'where' => 'civigeometry_geometry_entity.entity_id',
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
          'add' => NULL,
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Entity Table'),
          'description' => E::ts('entity table that is associated with this geometry'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civigeometry_geometry_entity.entity_table',
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
          'add' => NULL,
        ],
        'geometry_id' => [
          'name' => 'geometry_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Geometry ID'),
          'description' => E::ts('FK to Geometry Table'),
          'required' => TRUE,
          'where' => 'civigeometry_geometry_entity.geometry_id',
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
          'FKClassName' => 'CRM_CiviGeometry_DAO_Geometry',
          'add' => NULL,
        ],
        'expiry_date' => [
          'name' => 'expiry_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Expiry Date'),
          'description' => E::ts('When Should this geometry entity relationship expire'),
          'required' => FALSE,
          'where' => 'civigeometry_geometry_entity.expiry_date',
          'default' => NULL,
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
          'add' => NULL,
        ],
        'reason' => [
          'name' => 'reason',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Reason'),
          'description' => E::ts('The reason for the relationship between the geometry and entity'),
          'required' => FALSE,
          'maxlength' => 0,
          'size' => CRM_Utils_Type::TWO,
          'where' => 'civigeometry_geometry_entity.reason',
          'default' => NULL,
          'table_name' => 'civigeometry_geometry_entity',
          'entity' => 'GeometryEntity',
          'bao' => 'CRM_CiviGeometry_DAO_GeometryEntity',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'OptionGroup_geom_entity_relationship_reason',
            'optionEditPath' => 'civicrm/admin/options/OptionGroup_geom_entity_relationship_reason',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'etry_geometry_entity', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'etry_geometry_entity', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_entity_table_geometry_id_entity_id' => [
        'name' => 'index_entity_table_geometry_id_entity_id',
        'field' => [
          0 => 'entity_table',
          1 => 'geometry_id',
          2 => 'entity_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civigeometry_geometry_entity::1::entity_table::geometry_id::entity_id',
      ],
      'index_expiry_date' => [
        'name' => 'index_expiry_date',
        'field' => [
          0 => 'expiry_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civigeometry_geometry_entity::0::expiry_date',
      ],
      'index_entity_table_entity_id' => [
        'name' => 'index_entity_table_entity_id',
        'field' => [
          0 => 'entity_table',
          1 => 'entity_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civigeometry_geometry_entity::0::entity_table::entity_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
