-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
---- /*******************************************************
-- *
-- * Clean up the existing tables-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civigeometry_geometry_overlap_cache`;
DROP TABLE IF EXISTS `civigeometry_geometry_entity`;
DROP TABLE IF EXISTS `civigeometry_geometry_collection_geometry`;
DROP TABLE IF EXISTS `civigeometry_geometry_collection`;
DROP TABLE IF EXISTS `civigeometry_geometry`;
DROP TABLE IF EXISTS `civigeometry_geometry_type`;
DROP TABLE IF EXISTS `civigeometry_geometry_collection_type`;

SET FOREIGN_KEY_CHECKS=1;